# Generated by Django 3.0.8 on 2020-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
